# Generated by Django 5.2.8 on 2026-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('Manager', 'Manager'), ('HR', 'HR')])),
            ],
        ),
    ]
