# Generated by Django 5.2.8 on 2026-01-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Manager', 'Manager'), ('HR', 'HR')], default='Manager'),
        ),
    ]
